'''
title: "wiki masking and data indexing"
author: "Simon Sacher"
date: "October 23,  2025"
output:
    html_document: default
    pdf_document: default
    word_document: default
'''


```{r setup, include=FALSE}

Sys.setenv(R_LIBS_USER = "~/R/library1/")

library("knitr")

knitr::opts_chunk$set(echo = TRUE)
```


# Wiki entry: masking and data(frame) indexing

## masking
```{r masking, eval=FALSE}

X <- c(1:100)

mask1 <- intersect(c(1,3,5), c(1,2,3))

X[mask1]
```

## dataframes

```{r dataframe, eval=TRUE, echo=TRUE}

setwd("~/r-projects/intro_to_programming")
#df <- read.csv2("https://raw.githubusercontent.com/wegmann/R_data/master/Steigerwald_sample_points_all_data_subset_withNames.csv", sep=",")
#df <- read.csv2("./data/Steigerwald.csv", sep=",")

library("tidyverse")
df <- read_csv("https://raw.githubusercontent.com/wegmann/R_data/master/Steigerwald_sample_points_all_data_subset_withNames.csv")
```

### indexing dataframe
```{r indexing and plotting,  eval=TRUE, echo=TRUE}
print(df[,3]) # select column 3 of df

print(df[1, ]) # select row 1 of df

# example selection
y <- 350 # hm
x <- 10 # lc equals

plotdf <- df[(df$SRTM < y) & (df$LUCAS_LC == x),]
plot(plotdf$SRTM, plotdf$L8.ndvi)
```
